name: SystemPlugin
version: 1.0.2
main: Sp.System.SystemPlugin
author: Contratos
api-version: 1.13

commands:
  system:
    description: Comando principal del sistema.
    usage: /system
  spawn:
    description: Teletransportarse al área inicial.
    usage: /spawn
  Tienda:
    description: Acceso a la tienda.
    usage: /Tienda
  enderchest:
    description: Abrir el EnderChest.
    usage: /enderchest
    aliases:
      - ec
  tienda:
    description: Acceso a la tienda.
    usage: /tienda
  togglezone:
    description: Activa o desactiva zonas específicas.
    usage: /togglezone
  tpa:
    description: Enviar una solicitud de teletransporte a otro jugador.
    usage: /tpa <jugador>
  tpaccept:
    description: Aceptar una solicitud de teletransporte.
    usage: /tpaccept
  tpdeny:
    description: Rechazar una solicitud de teletransporte.
    usage: /tpdeny
  tpyes:
    description: Alternativa para aceptar solicitudes de teletransporte.
    usage: /tpyes
  tpno:
    description: Alternativa para rechazar solicitudes de teletransporte.
    usage: /tpno
  warp:
    description: Teletransportarse a un warp específico.
    usage: /warp <warp>
    aliases:
      - warps
      - Menu
      - warpsmenu
  warpcreate:
    description: Crear un nuevo warp.
    usage: /warpcreate <nombre> <warp/command> <slot> <permiso>
  reloadwarp:
    description: Recargar la configuración de los warps.
    usage: /reloadwarp
  pmsg:
    description: Envía un mensaje privado a un jugador.
    usage: /pmsg <jugador> <mensaje>
  actionbar:
    description: Envía un mensaje al ActionBar.
    usage: /actionbar <all|player> <mensaje>
  hcreload:
    description: Recargar la configuración del HideCommand.
    usage: /hcreload
